/* Copyright 2012 Google Inc. All rights reserved. */(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){
var k=this,aa=null;var ba=function(){},r=function(a){return"function"==typeof a},x=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},ca=function(a,b){if(Array.prototype.indexOf){var d=a.indexOf(b);return"number"==typeof d?d:-1}for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1},da=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},ea=function(a){return Math.round(Number(a))||0},y=function(){this.prefix="gtm.";this.Z={}};y.prototype.set=function(a,b){this.Z[this.prefix+a]=b};
y.prototype.get=function(a){return this.Z[this.prefix+a]};y.prototype.contains=function(a){return void 0!==this.get(a)};
var fa=function(a,b,d){try{return a["3"](a,b||ba,d||ba)}catch(c){}return!1},ga=function(a,b){function d(c,b){a.contains(c)||a.set(c,[]);a.get(c).push(b)}for(var c=da(b).split("&"),e=0;e<c.length;e++)if(c[e]){var f=c[e].indexOf("=");0>f?d(c[e],"1"):d(c[e].substring(0,f),c[e].substring(f+1))}},ha=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},ia=function(a){this.list=[];if(x(a))for(var b=0;b<a.length;b++)this.list.push(String(a[b]))},ja=function(a,b){var d=b["3"],
c;if(!(c=0<=ca(a.list,d.b)))e:{for(var e=a.list,f=d.c||[],g=new y,h=0;h<e.length;h++)g.set(e[h],!0);for(h=0;h<f.length;h++)if(g.get(f[h])){c=!0;break e}c=!1}return c},ka=function(a){for(var b=0;b<a.length;b++)a[b]()},la=function(){var a=this;this.p=!1;this.J=[];this.I=[];this.va=function(){a.p||ka(a.J);a.p=!0};this.ua=function(){a.p||ka(a.I);a.p=!0}},ma=function(){this.L=[];this.o=0};ma.prototype.addListener=function(a){this.L.push(a)};
var na=function(a,b){if(!b.p){a.o++;var d=function(){0<a.o&&a.o--;0<a.o||ka(a.L)};b.J.push(d);b.I.push(d)}};var A=window,B=document,D=function(a,b){var d=A[a],c="var "+a+";";if(k.execScript)k.execScript(c,"JavaScript");else if(k.eval)if(null==aa&&(k.eval("var _et_ = 1;"),"undefined"!=typeof k._et_?(delete k._et_,aa=!0):aa=!1),aa)k.eval(c);else{var e=k.document,f=e.createElement("script");f.type="text/javascript";f.defer=!1;f.appendChild(e.createTextNode(c));e.body.appendChild(f);e.body.removeChild(f)}else throw Error("goog.globalEval not available");A[a]=void 0===d?b:d;return A[a]},F=function(a,b,d){return("http:"==
A.location.protocol?b:a)+d},oa=function(a){var b=B.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},pa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},G=function(a,b,d){var c=B.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;pa(c,b);d&&(c.onerror=d);oa(c)},qa=function(a,b){var d=B.createElement("iframe");d.height="0";d.width="0";d.style.display="none";d.style.visibility=
"hidden";oa(d);pa(d,b);void 0!==a&&(d.src=a);return d},I=function(a,b,d){var c=new Image(1,1);c.onload=function(){c.onload=null;b&&b()};c.onerror=function(){c.onerror=null;d&&d()};c.src=a},J=function(a,b,d,c){a.addEventListener?a.addEventListener(b,d,!!c):a.attachEvent&&a.attachEvent("on"+b,d)},L=function(a){A.setTimeout(a,0)},ra=!1,sa=[],M=function(a){if(!(a&&"readystatechange"==a.type&&"interactive"!=B.readyState&&"complete"!=B.readyState||ra)){ra=!0;for(var b=0;b<sa.length;b++)sa[b]()}},ta=0,ua=
function(){if(!ra&&140>ta){ta++;try{B.documentElement.doScroll("left"),M()}catch(a){A.setTimeout(ua,50)}}},va=!1,wa=[],xa=function(){if(!va){va=!0;for(var a=0;a<wa.length;a++)wa[a]()}};var N=new y,ya=ba,O=[],za=!1,Aa=function(a){var b=!1;return function(){!b&&r(a)&&L(a);b=!0}},Ca=function(){for(var a=!1;!za&&0<O.length;){za=!0;var b;var d=O.shift(),c=void 0;for(c in d)d.hasOwnProperty(c)&&N.set(c,d[c]);var e=d.event;if(e){var f=Aa(d.eventCallback),g=d.eventTimeout;g&&A.setTimeout(f,Number(g));b=ya(e,f)}else b=!1;a=b||a;za=!1}return!a};var Da=null;var _e=function(){return Da};_e.b="e";var _f=function(){return String(N.get("gtm.referrer")||B.referrer)};_f.b="f";
var Ea=B.createElement("a"),Fa=function(a){var b=A.location,d=b.hash?b.href.replace(b.hash,""):b.href,c=N.get("gtm.url");c&&(Ea.href=d=String(c),b=Ea);
return d},_u=Fa;_u.b="u";var _eq=function(a){return String(a["0"])==String(a["1"])};_eq.b="eq";var _re=function(a){return RegExp(a["1"],a[""]?"i":void 0).test(a["0"])};_re.b="re";var Na=function(a){return function(b){b=b||A.event;if(!(b.defaultPrevented||!1===b.returnValue||b.Ba&&b.Ba())){var d=b.target||b.srcElement||{};if("LINK_CLICK"==a){for(var c=d,e=0;c&&"a"!=String(c.tagName).toLowerCase()&&100>e;e++)c=c.parentElement;c&&"a"!=String(c.tagName).toLowerCase()&&(c=null);d=c}if(d){var f={},g;e:{var h=d,l={eventTimeout:2E3,"gtm.element":h,"gtm.elementClasses":h.className,"gtm.elementId":h.id,"gtm.elementTarget":h.target};switch(a){case "LINK_CLICK":l.event="gtm.linkClick";
l["gtm.elementUrl"]=h.href;l.eventCallback=Ka(h,f);break;case "FORM_SUBMIT":l.event="gtm.formSubmit";l["gtm.elementUrl"]=h.action;l.eventCallback=La(h,f);break;default:g=!0;break e}g=A["dataLayer"].push(l)}f.simulateDefault=!g;if(!g){var p=Ma(d).toLowerCase();switch(p){case "_blank":f.targetWindow=A.open("","gtm_autoEvent_"+(new Date).getTime());case "":case "_parent":case "_self":case "_top":break;default:A.frames[p]||(f.targetWindow=A.open("",p))}b.preventDefault&&b.preventDefault()}return b.returnValue=
g}return!0}}},Ma=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "form":b="_self"}return b},Ka=function(a,b){return function(){if(b.simulateDefault)if(b.targetWindow)b.targetWindow.location.href=a.href;else{var d=Ma(a).toLowerCase();if("_blank"==d||"_self"==d||"_top"==d||"_parent"==d)d=d.substring(1);A.frames[d].location.href=a.href}}},La=function(a,b){return function(){if(b.simulateDefault){var d;b.targetWindow&&(d=a.target,a.target=b.targetWindow.name);a.submit();
b.targetWindow&&(a.target=d)}}},Oa=function(a){var b;switch(a){case "LINK_CLICK":b="click";break;case "FORM_SUBMIT":b="submit";break;default:return}J(B,b,Na(a),!1)};var P,Qa,Ra,Sa,Ta=function(){return k.navigator?k.navigator.userAgent:null};Sa=Ra=Qa=P=!1;var Q;if(Q=Ta()){var Ua=k.navigator;P=0==Q.lastIndexOf("Opera",0);Qa=!P&&(-1!=Q.indexOf("MSIE")||-1!=Q.indexOf("Trident"));Ra=!P&&-1!=Q.indexOf("WebKit");Sa=!P&&!Ra&&!Qa&&"Gecko"==Ua.product}var S=Qa,Va=Sa,Wa=Ra,Xa=function(){var a=k.document;return a?a.documentMode:void 0},Ya;
e:{var ab="",T;if(P&&k.opera)var bb=k.opera.version,ab="function"==typeof bb?bb():bb;else if(Va?T=/rv\:([^\);]+)(\)|;)/:S?T=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Wa&&(T=/WebKit\/(\S+)/),T)var cb=T.exec(Ta()),ab=cb?cb[1]:"";if(S){var db=Xa();if(db>parseFloat(ab)){Ya=String(db);break e}}Ya=ab}
var eb=Ya,fb={},U=function(a){var b;if(!(b=fb[a])){for(var d=0,c=String(eb).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,e.length),g=0;0==d&&g<f;g++){var h=c[g]||"",l=e[g]||"",p=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var q=p.exec(h)||["","",""],n=m.exec(l)||["","",""];if(0==q[0].length&&0==n[0].length)break;d=((0==q[1].length?0:parseInt(q[1],10))<(0==n[1].length?0:parseInt(n[1],10))?-1:(0==q[1].length?
0:parseInt(q[1],10))>(0==n[1].length?0:parseInt(n[1],10))?1:0)||((0==q[2].length)<(0==n[2].length)?-1:(0==q[2].length)>(0==n[2].length)?1:0)||(q[2]<n[2]?-1:q[2]>n[2]?1:0)}while(0==d)}b=fb[a]=0<=d}return b},gb=k.document,hb=gb&&S?Xa()||("CSS1Compat"==gb.compatMode?parseInt(eb,10):5):void 0;if(Va||S){var ib;if(ib=S)ib=S&&9<=hb;ib||Va&&U("1.9.1")}S&&U("9");var nb=function(a,b){var d="";S&&!jb(a)&&(d='<script>document.domain="'+document.domain+'";\x3c/script>'+d);var c="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+d+"</head><body>"+b+"</body></html>";if(kb)a.srcdoc=c;else if(lb){var e=a.contentWindow.document;e.open("text/html","replace");e.write(c);e.close()}else mb(a,c)},kb=Wa&&"srcdoc"in document.createElement("iframe"),lb=Va||Wa,mb=function(a,b){S&&(U(7)&&!U(10))&&ob(b)&&(b=pb(b));var d=function(){a.contentWindow.goog_content=
b;a.src="javascript:window.goog_content"};S&&!jb(a)?qb(a,d):d()},jb=function(a){try{return Boolean(a.contentWindow.document)}catch(b){return!1}},rb=0,qb=function(a,b){var d="goog_rendering_callback"+rb++;window[d]=b;S&&U(6)&&!U(7)?a.src="javascript:'<script>window.onload = function() { document.write(\\'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+d+";window.parent."+d+" = null;continuation()})()<\\\\/script>\\');document.close();};\x3c/script>'":
a.src="javascript:'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+d+";window.parent."+d+" = null;continuation();})()\x3c/script>'"},ob=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},pb=function(a){for(var b=unescape(encodeURIComponent(a)),d=Math.floor(b.length/2),c=[],e=0;e<d;++e)c[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(c[d]=b.charAt(b.length-1));return c.join("")};/*
 Copyright (c) 2013 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var Ab,Bb;
var Jb=function(a){return function(){}},Nb=function(a){return function(){}};var _sp=function(a,b,d){G("//www.googleadservices.com/pagead/conversion_async.js",function(){var c=A.google_trackConversion;r(c)?(c({google_conversion_id:a["4"],google_conversion_label:a["6"],google_custom_params:a["2"]||{}}),b()):d()},d)};_sp.b="sp";var nc=function(){this.g=[]};nc.prototype.set=function(a,b){this.g.push([a,b]);return this};nc.prototype.v=function(a){for(var b={},d=0;d<this.g.length;d++)b[X(this.g[d][0],a)]=X(this.g[d][1],a);return b};
for(var pc=function(a){this.index=a;this.v=function(b){return b&&ja(b,oc[a])?void 0:fa(oc[a])}},_M=function(a){return new pc(a)},rc=function(a){this.v=function(b){for(var d=[],c=0;c<a.length;c++)d.push(X(qc[a[c]],b));return d.join("")}},_T=function(a){return new rc(arguments)},sc=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}
this.v=function(d){if(a[0]instanceof pc&&b(8)&&b(16))return'google_tag_manager["GTM-LVPJ"].macro('+a[0].index+")";for(var c=String(X(a[0],d)),e=1;e<a.length;e++)c=V[a[e]](c);return c}},_E=function(a,b){return new sc(arguments)},X=function(a,b){var d=a;if(a instanceof pc||a instanceof nc||a instanceof rc||a instanceof sc)return a.v(b);if(x(a))for(var d=[],c=0;c<a.length;c++)d[c]=X(a[c],b);else if(a&&"object"==typeof a){var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=X(a[e],b))}return d},tc=function(a,
b){var d=b[a],c=d;if(d instanceof pc||d instanceof sc||d instanceof rc)c=d;else if(x(d))for(var c=[],e=0;e<d.length;e++)c[e]=tc(d[e],b);else if("object"==typeof d){var c=new nc,f;for(f in d)d.hasOwnProperty(f)&&c.set(b[f],tc(d[f],b))}return c},wc=function(a,b){for(var d=b?b.split(","):[],c=0;c<d.length;c++){var e=d[c]=d[c].split(":");0==a&&(e[1]=qc[e[1]]);if(1==a)for(var f=uc(e[0]),e=d[c]={},g=0;g<f.length;g++){var h=vc[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=uc(e[g])}return d},uc=function(a){var b=
[];if(!a)return b;for(var d=0,c=0;c<a.length&&d<xc;d+=6,c++){var e=a&&a.charCodeAt(c)||65;if(65!=e){var f=0,f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(d);2&f&&b.push(d+1);4&f&&b.push(d+2);8&f&&b.push(d+3);16&f&&b.push(d+4);32&f&&b.push(d+5)}}return b},xc=19,yc=[_re,_u,'url',_M(0),'.*',_eq,_e,'_event',_M(1),'gtm.js',_sp,'Remarketing Google','1044585254','nH5oCOCliwUQpraM8gM',1,_f,'referrer','event'],zc=[],Ac=0;Ac<yc.length;Ac++)zc[Ac]=tc(Ac,yc);
var qc=zc,vc=wc(0,"3:0,3:1,5:2,0:3,1:4,3:5,3:6,5:7,0:8,1:9,3:10,5:11,4:12,2:3,6:13,7:14,3:15,5:16,5:17"),oc=wc(1,"G,AD,AAw,ABAB"),Bc=wc(1,"Z,gM"),Y=wc(1,"AwP"),Cc=wc(2,"D:B::");var Jc=function(){var a=[];return function(b,d){if(void 0===a[b]){var c=Bc[b]&&X(Bc[b],d);a[b]=[c&&fa(c),c]}return a[b]}},Kc=function(a,b){for(var d=b[0],c=0;c<d.length;c++)if(!a.i(d[c],a.d)[0])return!1;for(var e=b[2],c=0;c<e.length;c++)if(a.i(e[c],a.d)[0])return!1;return!0},Lc=ya=function(a,b){Da=a;for(var d=N.get("tagTypeBlacklist"),c={name:a,wa:b||ba,t:uc(),u:uc(),i:Jc(),d:new ia(d)},e=0;e<Cc.length;e++)if(Kc(c,Cc[e])){for(var f=c,g=Cc[e],h=g[1],l=0;l<h.length;l++)f.t[h[l]]=!0;for(var p=g[3],l=
0;l<p.length;l++)f.u[p[l]]=!0}var m=[];for(var q=0;q<xc;q++)if(c.t[q]&&!c.u[q])if(ja(c.d,Y[q])){}else{m[q]=X(Y[q],c.d);}c.M=m;for(var n=new ma,s=0;s<xc;s++)if(c.t[s]&&!c.u[s]&&!ja(c.d,Y[s])){var K=c.M[s],C=new la;C.J.push(Jb(K));C.I.push(Nb(K));na(n,C);fa(K,C.va,C.ua)}n.addListener(c.wa);0<n.o||ka(n.L);Da=null;return 0<c.M.length};var $={set:function(a,b){N.set(a,b)},event:function(a){Lc(a)},macro:function(a){var b=N.get("tagTypeBlacklist"),d;if(d=oc[a]){var c,e=new ia(b);c=X(oc[a],e);d=fa(c)}return d},N:{push:function(a){for(var b=arguments,d=0;d<b.length;d++)try{if(r(b[d][0]))b[d][0]();else $[b[d][0]].apply($,[].slice.call(b[d],1))}catch(c){}}},za:function(){var a=A["gtm"];if(a){var b=a.a;x(b)&&$.N.push.apply($.N,b);a.a=$.N;sa.push(function(){$.event("gtm.dom")});wa.push(function(){$.event("gtm.load")})}},Aa:function(){var a=
A.google_tag_manager;a||(a=A.google_tag_manager={});a["GTM-LVPJ"]||(a["GTM-LVPJ"]=$)}};$.Aa();$.za();(function(){var a=D("dataLayer",[]),b=A.google_tag_manager;sa.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});wa.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var d=a.push;a.push=function(){var b=[].slice.call(arguments,0);d.apply(a,b);O.push.apply(O,b);return Ca()};O.push.apply(O,a.slice(0));L(Ca)})();
if("interactive"==B.readyState||"complete"==B.readyState)M();else{J(B,"DOMContentLoaded",M);J(B,"readystatechange",M);if(B.createEventObject&&B.documentElement.doScroll){var Mc=!0;try{Mc=!A.frameElement}catch(Nc){}Mc&&ua()}J(A,"load",M)}"complete"===B.readyState?xa():J(A,"load",xa);var _vs="res_ts:1374773350681000,srv_cl:51503938,ds:live,cv:3";
})()
